# Site settings
title: ShopNow - 더욱 즐거운 온라인 쇼핑
description: '간편하고 다양한 상품을 판매하는 쇼핑 사이트입니다. '
url: 'https://goodhub1214.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true
timezone: Asia/Seoul

author:
  name: 'GoodHub'
  email: sili45953@gmail.com
  twitter_username:
  facebook_username: 
  github_username: 
  linkedin_username: 

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

